### ISSUE TITLE
[ASButtonNode] Title is truncated in ASButtonNode

### ISSUE THREAD

**Issue by suomalainen9890** [facebook/AsyncDisplayKit#1865]
I have a ASButtonNode which has static width and height. Originally the button node has a title, if later title of the button node changes to longer text, new title is truncated even though it takes not even half of the width of the button.

**Comment by appleguy** [comment]
@suomalainen9890 thanks for reporting this!  It should be fixed by this PR: https://github.com/facebook/AsyncDisplayKit/pull/1863

Could you test it out locally?  If you're able to provide a test project, we can verify it for you.  The PR mentioned should land in the next day, and will be in the next release.  cc @maicki

**Comment by suomalainen9890** [comment]
@appleguy : Thanks! Does it mean that I need to use this in the Podfile?
pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :commit => '9d1e669'

I have never tried to do similar thing before.

**Comment by maicki** [comment]
@suomalainen9890 Try to use this in your Podfile:

`pod 'AsyncDisplayKit', :git => 'https://github.com/maicki/AsyncDisplayKit.git', :branch => 'MSFixTextNodeTruncation'`

**Comment by suomalainen9890** [comment]
@maicki : thanks! I will try.

**Comment by suomalainen9890** [comment]
@maicki @appleguy It does not fix my problem. I will send a sample project here asap.

**Comment by suomalainen9890** [comment]
@maicki @appleguy : This is sample project, less than 100 lines of code. I could be doing something wrong here. Please take a look: https://github.com/tungvoduc/ADKBugTest

**Comment by maicki** [comment]
@suomalainen9890 Can you try out your example / main project with that fix: #1902 please. Thanks!

Furthermore in your example you have to move some code in the `ViewController.swift` otherwise the layout does fundamentally not really work:

```Swift
class ViewController: ASViewController {
    private let _scrollNode: ASScrollNode = ASScrollNode()
    private let _profileInfoNode = ProfileInfoNode()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.node.addSubnode(_profileInfoNode)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        // Do any additional setup after loading the view, typically from a nib.
        let size = _profileInfoNode.measureWithSizeRange(ASSizeRange(min: CGSize(width: node.bounds.size.width, height: 0), max: CGSize(width: node.bounds.size.width, height: 100))).size
        _profileInfoNode.frame = CGRect(origin: CGPointMake(0, 20), size: size)
    }

    init() {
        super.init(node: _scrollNode)
        self.edgesForExtendedLayout = UIRectEdge.Bottom
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by maicki** [comment]
Just want to follow up on this issue. I just looked into that again and the initial issue is fixed as the right behavior (relayout of the nodes are bubbling up) will occur if you tap the button.

That said the `ASTextNode` has currently a problem to provide the right size in certain circumstances after the attributed string changes. This is the same issue we have in #1841. If #1841 will be fixed this issue should be fixed fully too. I will let it closed and further investigation will be in #1841

**Comment by suomalainen9890** [comment]
I don't know why button title still not working for me even in version 1.9.90. Title is still truncated when changing title with longer one, and title is not aligned correctly when changing title with shorter one. But it is working in sample project and the code are pretty much the same.
