### ISSUE TITLE
`ASCollectionView` is only deallocating the visible nodes

### ISSUE THREAD

**Issue by bensarz** [facebook/AsyncDisplayKit#406]
We are creating some `ASCellNode` instances. Twelve (12) are being created but only eight (8) on are on screen. Without scrolling, simply navigating away from the controller, only the eight (8) that were visible on the screen get deallocated.
It is important to note that `calculateSizeThatFits:` seems to have an impact on this. Returning `CGSizeZero` triggers deallocation for all nodes. Returning any other size that causes some nodes to be off screen creates this problem.

The initialization of all twelves (12) node, and deallocation of our controller, followed by the deallocation of only visible nodes:

```
init | <Instance: 0x12fe4bd30>
init | <Instance: 0x12fe5bc50>
init | <Instance: 0x12fd57200>
init | <Instance: 0x12fd5a340>
init | <Instance: 0x12fd5c840>
init | <Instance: 0x12fe61e30>
init | <Instance: 0x12fd60c80>
init | <Instance: 0x12fe63490>
init | <Instance: 0x12fe66c90>
init | <Instance: 0x12fe69310>
init | <Instance: 0x12fd686d0>
init | <Instance: 0x12fd6b840>

[Controller] dealloc | This is such a beautiful thing.
[Instance] dealloc | 0x12fe4bd30
[Instance] dealloc | 0x12fe5bc50
[Instance] dealloc | 0x12fd57200
[Instance] dealloc | 0x12fd5a340
[Instance] dealloc | 0x12fd5c840
[Instance] dealloc | 0x12fe61e30
[Instance] dealloc | 0x12fd60c80
[Instance] dealloc | 0x12fe63490
```

This sounds like it could be a bug in the library, any help would be appreciated.
We're always available to provide more info if required.

Cheers! :beers:

**Comment by bensarz** [comment]
Digging deeper into this issue, it seems related the view hierarchy.
The nodes being added to the view hierarchy and subsequently being removed from the view hierarchy are being deallocated. The ones that never exit the view hierarchy never get deallocated.

```
2015-03-31 14:55:04:916 [12816:7307]  init | 0x156e46f10
2015-03-31 14:55:04:967 [12816:7307]  init | 0x156d53390
2015-03-31 14:55:04:991 [12816:7307]  init | 0x156e50f40
2015-03-31 14:55:05:036 [12816:7307]  init | 0x156d560c0
2015-03-31 14:55:05:058 [12816:7307]  init | 0x156e626f0
2015-03-31 14:55:05:089 [12816:7307]  init | 0x156e64560
2015-03-31 14:55:05:118 [12816:7307]  init | 0x156e696f0
2015-03-31 14:55:05:140 [12816:7307]  init | 0x156d5bc80
2015-03-31 14:55:05:172 [12816:7307]  init | 0x156d5d160
2015-03-31 14:55:05:189 [12816:7307]  init | 0x156e6e380
2015-03-31 14:55:05:208 [12816:7307]  init | 0x156e71b50
2015-03-31 14:55:05:218 [12816:7307]  init | 0x156e74b20
2015-03-31 14:55:05:401 [12816:7307]  init | 0x156d628d0
2015-03-31 14:55:05:453 [12816:7307]  init | 0x156e7bc30
2015-03-31 14:55:05:521 [12816:7307]  init | 0x156d68620
2015-03-31 14:55:05:570 [12816:7307]  init | 0x156e7e760

2015-03-31 14:55:06.298 [12816:606595] entering view hierarchy: 0x156e46f10
2015-03-31 14:55:06.336 [12816:606595] entering view hierarchy: 0x156d53390
2015-03-31 14:55:06.391 [12816:606595] entering view hierarchy: 0x156e50f40
2015-03-31 14:55:06.470 [12816:606595] entering view hierarchy: 0x156d560c0
2015-03-31 14:55:06.560 [12816:606595] entering view hierarchy: 0x156e626f0
2015-03-31 14:55:06.605 [12816:606595] entering view hierarchy: 0x156e64560
2015-03-31 14:55:06.639 [12816:606595] entering view hierarchy: 0x156e696f0
2015-03-31 14:55:06.667 [12816:606595] entering view hierarchy: 0x156d5bc80
2015-03-31 14:55:07.687 [12816:606595] entering view hierarchy: 0x156d5d160
2015-03-31 14:55:07.705 [12816:606595] entering view hierarchy: 0x156e6e380
2015-03-31 14:55:07.725 [12816:606595] entering view hierarchy: 0x156e71b50
2015-03-31 14:55:07.756 [12816:606595] entering view hierarchy: 0x156e74b20
2015-03-31 14:55:07.791 [12816:606595] entering view hierarchy: 0x156d628d0
2015-03-31 14:55:07.834 [12816:606595] entering view hierarchy: 0x156e7bc30
2015-03-31 14:55:07.870 [12816:606595] entering view hierarchy: 0x156d68620
2015-03-31 14:55:07.880 [12816:606595] entering view hierarchy: 0x156e7e760

2015-03-31 14:55:17.515 [12816:606595] exiting view hierarchy: 0x156e46f10
2015-03-31 14:55:17.516 [12816:606595] exiting view hierarchy: 0x156d53390
2015-03-31 14:55:17.520 [12816:606595] exiting view hierarchy: 0x156e50f40
2015-03-31 14:55:17.534 [12816:606595] exiting view hierarchy: 0x156d560c0
2015-03-31 14:55:17.545 [12816:606595] exiting view hierarchy: 0x156e626f0
2015-03-31 14:55:17.552 [12816:606595] exiting view hierarchy: 0x156e64560
2015-03-31 14:55:17.558 [12816:606595] exiting view hierarchy: 0x156e696f0
2015-03-31 14:55:17.565 [12816:606595] exiting view hierarchy: 0x156d5bc80

2015-03-31 14:55:17:738 [12816:b0b] [controller] dealloc | This is such a beautiful thing.
2015-03-31 14:55:17:785 [12816:b0b] dealloc | 0x156d5bc80
2015-03-31 14:55:17:798 [12816:b0b] dealloc | 0x156e696f0
2015-03-31 14:55:17:809 [12816:b0b] dealloc | 0x156e64560
2015-03-31 14:55:17:820 [12816:b0b] dealloc | 0x156e626f0
2015-03-31 14:55:17:833 [12816:b0b] dealloc | 0x156d560c0
2015-03-31 14:55:17:846 [12816:b0b] dealloc | 0x156e50f40
2015-03-31 14:55:17:857 [12816:b0b] dealloc | 0x156d53390
2015-03-31 14:55:17:868 [12816:b0b] dealloc | 0x156e46f10
```

**Comment by bensarz** [comment]
Also seems to be a similar problem to https://github.com/facebook/AsyncDisplayKit/issues/38

**Comment by adremeaux** [comment]
I'm actually finding the opposite right now: the collection view is deallocating everything except the nodes that were visible at the time of teardown. I haven't yet found a solution to this issue, so I'm working around it by identifying the leaked nodes and forcing them to remove all of their content. It's a hack but at least then what is leaking is very minimal (just a shell of an ASDisplayNode) rather than the whole, content-filled cell.

**Comment by appleguy** [comment]
I just merged a diff that should resolve any retain cycles on full teardown of the view.  #437 

Could you please re-test, and definitely re-open the task (or a new one) if it is still apparent?  Thanks much!

**Comment by ERussel** [comment]
I can confirm that the issue is still present. For example, when i call reloadData for collectionView, invisible nodes would not be deallocated. As i understand from ASRangeHandlerRender code, invisible nodes are added to global working window to activate offscreen rendering, but i don't see any workaround to remove them from superview in DELETE_NODES call.
