### ISSUE TITLE
ASCollectionView Sample project crashes when poping a copied CollectionViewConroller

### ISSUE THREAD

**Issue by drinking** [facebook/AsyncDisplayKit#834]
AsyncDisplayKit 1.9.1

*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <CALayerArray: 0x7f9276971480> was mutated while being enumerated.'

**Comment by 1nput0utput** [comment]
@drinking this may be related to #832.

**Comment by appleguy** [comment]
@1nput0utput you're right.  @drinking this is fixed in master and I did bump the git tag to include the fix for 1.9.1 as well.  Try pod install again and /please reopen this task/ if it does not address the issue.  If it doesn't, I may need to roll a 1.9.2 just for that commit, which would be unfortunate but is easy for me to do.  Thank you for reporting.

**Comment by drinking** [comment]
@appleguy It seems that code on Pod is still not the latest. I'm afraid you have to roll a 1.9.2.
