### ISSUE TITLE
[Supplementary Nodes] ASCollectionView crashed due to nil supplementary node?

### ISSUE THREAD

**Issue by stowy** [facebook/AsyncDisplayKit#893]
I'm not sure why this is occurring, but when layoutSubviews is called on my ASCollectionViewController, it calls 
```objc 
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
```
and the node that is provided from 
```objc
ASCellNode *node = [_dataController supplementaryNodeOfKind:kind atIndexPath:indexPath];
```
is nil. Therefore it is not stored in `_completedNodes`.

I've been scrutinizing this section of code in `ASCollectionDataController.mm`:

```objc
- (void)willInsertSections:(NSIndexSet *)sections
{
  [_pendingNodes enumerateKeysAndObjectsUsingBlock:^(NSString *kind, NSMutableArray *nodes, BOOL *stop) {
    NSMutableArray *sectionArray = [NSMutableArray arrayWithCapacity:sections.count];
    for (NSUInteger i = 0; i < sections.count; i++) {
      [sectionArray addObject:[NSMutableArray array]];
    }
    
    [self insertSections:sectionArray ofKind:kind atIndexSet:sections completion:nil];
    [self batchLayoutNodes:nodes ofKind:kind atIndexPaths:_pendingIndexPaths[kind] completion:nil];
    _pendingNodes[kind] = nil;
    _pendingIndexPaths[kind] = nil;
  }];
}
```

This is supposed to insert the pendingSections into the completed sections, however I may be missing something but the nodes never actually get added so I wonder if the completedNodes for the supplementary views ever get populated? It doesn't seem to be a problem with the rowNodes, only kind UICollectionElementKindSectionHeader at this point.

If this code works fine, then perhaps there is a race condition where layoutSubviews is being called when the completedNodes are being populated? This event seems to occur when I scroll to the bottom of my collection view, when the first UICollectionElementKindSectionHeader view is about to be displayed. It leads me to believe the supplementary view is not being correctly cached or I have a broken implementation.

**Comment by appleguy** [comment]
@stowy Thanks for reporting.  What kind of collection layout are you using?  Supplementary nodes are supported out of the box with Flow Layouts, but for custom layouts, it is necessary that you implement the ...LayoutInspecting API / delegate.  An example of this is here: https://github.com/facebook/AsyncDisplayKit/pull/879/files  The author of the example is also the author of the supplementary node support, so if you provide more detail on your implementation, we should be able to help resolve any issues.

@levi in any case, we should ensure that it is very difficult to cause a crash even if LayoutInspecting or something else is not implemented correctly.

@stowy can you please include a /full/ crash log of where the crash is occurring, include any console logs (such as strings printed by an NSException), and describe what action causes the crash? (simply launching the app / viewing the collection, or if it requires scrolling, etc)

**Comment by stowy** [comment]
Thanks @appleguy for the quick response. I am using a plain `UICollectionViewFlowLayout`. Not subclassed.  I have done a quick conversion of my existing UICollectionView implementation to ASCollectionViewController but am returning the correct ASCellNodes for all views.

It occurs the first time the header supplementary view is due to be displayed.

Here are screenshots of the debugging and the console output:
[ConsoleOutput.txt](https://github.com/facebook/AsyncDisplayKit/files/46449/ConsoleOutput.txt)
<img width="1125" alt="screenshot 2015-11-28 17 39 21" src="https://cloud.githubusercontent.com/assets/5924628/11454916/cbdf50fe-95f6-11e5-8bbf-edc7acb5cacf.png">
<img width="1141" alt="screenshot 2015-11-28 17 39 00" src="https://cloud.githubusercontent.com/assets/5924628/11454917/cbfdef28-95f6-11e5-9471-3bf5c6cde95f.png">
<img width="816" alt="screenshot 2015-11-28 17 38 13" src="https://cloud.githubusercontent.com/assets/5924628/11454919/cbfe9b76-95f6-11e5-9ae2-b68e7550b044.png">
<img width="1169" alt="screenshot 2015-11-28 17 37 56" src="https://cloud.githubusercontent.com/assets/5924628/11454918/cbfe94aa-95f6-11e5-957e-c9320a267ab2.png">

**Comment by appleguy** [comment]
@stowy awesome, thanks for the details.  What commit hash is the HEAD of your version of ASDK?  Can you re-link your project against the latest master version and let me know if the crash either goes away or changes?

I notice in the stack some stuff about GPRaptorEngine, and then a trampoline call.  Are you absolutely certain that the asyncDataSource and asyncDelegate are in a consistent state?  Remember, ASCollectionView has special behavior that creates a separation between the UIKit layer and the ASDK layer to facilitate asynchronous computation, so if your subclass of ASCollectionView is doing fancy stuff at the UIKit layer (such as calling UICollectionView methods that aren't bridged / implemented by ASCollectionView), it could cause a variety of issues like this.

It may well be that the bug is in ASDK, but it would be important to know if the reason is that ASDK is missing an override for some UICollectionView method that we didn't think of which your class may be using.  cc @levi

**Comment by levi** [comment]
@stowy I'm curious to see your implementation of `ASCollectionViewDelegateFlowLayout` and `ASCollectionViewDataSource`. Posting those will help shed some light into why the initial supplementary node is not being populated in the data source.

**Comment by stowy** [comment]
Hi @appleguy and @levi, I have tried reloading the source using the latest commit on master, and no changes. I have re-reviewed the collection view flow layout delegate `ASCollectionViewDelegateFlowLayout` and datasource methods and stepped through the internal implementation of the delegate, the correct sizes and nodes are being returned. 

What I still cannot see is where the supplementary nodes are added to the completed nodes, as you can see I am returning the supplementary node in my datasource and it is being added to the pending nodes, but pending nodes is then set to nil, without the node being added anywhere. The nil error is coming when the data controller tries to find the supplementary node in its _completedNodes array.

**Comment by levi** [comment]
@stowy sounds like there's a misconfiguration in the data source of the collection view. If you'd be able to share with me a generic version of your `ASCollectionViewDataSource` and `ASCollectionViewDelegateFlowLayout` implementation, I'll be able to help pin-point where this issue is coming from. This also sounds like something that I'll be able to prevent happening in the future with an assertion. Send it over when you get a chance, would be super helpful to learn about alternative use implementations of supplementary nodes.

**Comment by stowy** [comment]
OK thanks Levi will do.  I will review your example and see if I can figure
out where my current implementation differs. If i don't work it out I'll
send you the code example,  otherwise I'll let you know what I find.

**Comment by stowy** [comment]
Hi @levi I think the issue may be in inserting and deleting sections. I've tried modifying your sample code to do a  simple insert / delete operation but I'm not having much luck.

Can you check out the example at https://dl.dropboxusercontent.com/u/5157106/ASCollectionView-Modified.zip and see what you think?

**Comment by levi** [comment]
@stowy thanks including the simple project!  I'll have some time for the next couple days to pull it down and help diagnose this issue.

**Comment by stowy** [comment]
cool thanks @levi. The reload with supplementary views works if you just call `reloadData` but if you want to animate adding and removing of sections with the supplementary views it's not a good time. I'm pretty sure this is the main issue in my larger project.

**Comment by appleguy** [comment]
@stowy - thanks for taking the time to make the sample app.  That will really help us move more quickly here.

I am tagging this for 1.9.3 and will try my absolute best to get a fix rolled out this coming Sunday night with that release.

**Comment by stowy** [comment]
Sounds great thanks guys much appreciated.

**Comment by appleguy** [comment]
@levi thanks so much for fixing this on a Sunday night!  @stowy, please try it out and let us know either way.

**Comment by stowy** [comment]
Hey guys thanks heaps, I will check it out and let you know tomorrow.

**Comment by stowy** [comment]
Just checked in the sample project and the original project and in both cases the issue is resolved, thanks @levi and @appleguy

**Comment by levi** [comment]
Glad to hear it, @stowy!

**Comment by benjaminhorner** [comment]
Hi guys,
Sorry to cast bad news, but it seems the issue still lies here. I have a collectionViewNode with a supplementaryView.

The culprit is this line of code:
```
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {        
        if collectionViewData.count > 0 {
            return CGSize(width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.width)
        }
        else {
           return CGSize.zero
        }
}
```
This works fine until I call **reloadData()** or **insertItemsAtIndexPaths**…

If I remove this, the error goes away… but so does my supplementaryView :(
