### ISSUE TITLE
[ASCollectionView] Supplementary node access out of bounds when reloading section.

### ISSUE THREAD

**Issue by wieseljonas** [facebook/AsyncDisplayKit#986]
Hi Guys long time no speak. I finally had time to try and start implementing Supplementary view from @levi.  

I manage to display the view fine but when I scroll back to it I get the following error `Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'`

    - (ASCellNode *)supplementaryNodeOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath {
       ASDisplayNodeAssertMainThread();
       return [self completedNodesOfKind:kind][indexPath.section][indexPath.item];
    }

At the moment my node is a hybrid as it is a very complex layout I haven't yet fully implemented it in Nodes. Maybe this is the issue?

Here is my `ASCellNode`

    class IndividualHeaderNode: ASCellNode {
    var header : IndividualHeaderView!
    override func didLoad() {
        self.view.addSubview(header)
        header.fillSuperview()
        super.didLoad()
    }
    
    init(individualId: String, delegate: MakoFeedViewController) {
        super.init()
        header = IndividualHeaderView()
        header.individualId = individualId
        header.delegate = delegate
    }
    
    override func calculateSizeThatFits(constrainedSize: CGSize) -> CGSize {
        var cardSize = CGSizeZero
        cardSize.width = UIScreen.mainScreen().bounds.size.width
        cardSize.height = 260 + 40 + (UIScreen.mainScreen().bounds.size.width * 0.4) + 8
        return cardSize
    }
    }

Thank you for your help

**Comment by appleguy** [comment]
cc @levi.  @wieseljonas could you confirm what commit of ASDK you're using?  An issue like this was fixed in master, and is about to go out with 1.9.4 in the next couple days.  I want to make absolutely sure your issue is resolved before I launch the release, if at all possible.  Feel free to email me at asyncdisplaykit@gmail.com too and I'll give you my iMessage for faster coordination..

**Comment by levi** [comment]
@wieseljonas this doesn't have anything to do with your node, rather how the data source is interfacing with the ASCollectionView. If 1.9.4 doesn't fix your issue, please post your data source implementation and we can help diagnose.

**Comment by wieseljonas** [comment]
Hi guys I just gave master a spin and I still get the same issue.

**Comment by wieseljonas** [comment]
here is my data source implementation

       
    var feedData: [AnyObject] = []  {
        willSet {
            assert(!dataSourceLocked, "Could not update data source when it is locked!")
        }
    }


    func collectionView(collectionView: ASCollectionView!, nodeForSupplementaryElementOfKind kind: String!, atIndexPath indexPath: NSIndexPath!) -> ASCellNode! {
                let node = IndividualHeaderNode(individualId: individualId, delegate: self)
                individualHeaderView = node.header
                return node
    }

**Comment by appleguy** [comment]
@wieseljonas I think I see the issue.  Thank you for trying 1.9.4 and providing more information.

- Can you paste the entire backtrace for the crash?  This is essential info as there are often multiple possible call paths to methods.
- If you drop in some of this code to any of our examples, such as examples/ASCollectionView or examples/CustomCollectionView, can you trigger the crash?  Though I can likely create a speculative fix without reproduction, I'd rather not have to expect you to reply on Christmas Eve or Day to verify the fix!

Cheers - hope you are with family!

**Comment by wieseljonas** [comment]
@levi @appleguy 

I think I found what was causing the issue. I was using reloadSections(), Now I use reloadData() and it works. 

Merry Xmas to you all!

**Comment by appleguy** [comment]
@wieseljonas I'm glad you were able to solve the issue - however, that sounds a bit like a workaround rather than solving the root cause.  Based on your access to the code that we can't see, does it make sense to you why the reloadSections version would have crashed (e.g. inconsistent data at some moment?)

**Comment by wieseljonas** [comment]
@appleguy I'm not sure. I think the easiest is if I try a do a sample project that reproduces the issue and share it with you guys. If that makes sense.

**Comment by appleguy** [comment]
@wieseljonas that would be fantastic, if you have time!  I'll leave this issue open even if you don't have time right now, but punt it to a later release in that case since you have a workaround.  I'm glad you are unblocked, but also want to make sure others don't get stuck on this.

**Comment by wieseljonas** [comment]
Easy way to reproduce it is to try and use reloadsections in the CustomCollectionView example.

e.g adding this after the collectionView is added to the view.

    NSRange range = NSMakeRange(0, 1);
    NSIndexSet *section = [NSIndexSet indexSetWithIndexesInRange:range];
    [_collectionView reloadSections:section];

**Comment by levi** [comment]
Could be an internal issue of the data controller. Will take a look at this when I'm back in civilization.

**Comment by appleguy** [comment]
@wieseljonas thanks so much for the reproduction steps!  I can confirm the issue.  Shouldn't be more than a few days to a fix.  As you can see if you look into git log on the collection or table components, I'm hacking there in rolling intervals, so this isn't too much of a diversion from my planned work.

I also notice the flashing upon reloading the first section when scrolled down.  Some of that may be fixable; some might be inherent with what the user is requesting.  We may want to default-on neverShowPlaceholders in those cases when content is onscreen, which is certainly what UIKit does; we have the advantage of approximately half the main thread blocking time in such a situation, as -recursivelyEnsureDisplaySynchronously:YES will simply pause the main thread waiting on a multithreaded background operation that processes the layout and display for each item independently.

**Comment by appleguy** [comment]
@wieseljonas I'm pretty confident this is fixed - not just a workaround, but the right fix.  The code was missing a fairly critical call for this case, which hadn't been found because supplementary nodes are still fairly new to ASDK and not widely used (the bug only applied to single-section reloading; even single-section inserting worked correctly).

Please try it out and report any other issues you discover!

**Comment by wieseljonas** [comment]
Fixed it for me! However it would be great to also be able to get the supplementaryNode in order to update it!

Thank you @appleguy
